apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeploymentservice
spec:
  replicas: 5
  template: #pod def. & if add you want to replica so add
    metadata:
      name: nginxdeploymentservice
      labels:
        app: nginxdeploymentservice
        type: webServerservice
    spec:
      containers:
        - name: nginxdeploymentservice
          image: nginx
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      type: webServerservice
